title: AP CSA Blogs
description: "August 2023 to June 2024"
owner_name: Aiden Huynh
github_username: aidenhuynh
baseurl: "/Epic_CSA"
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
# remote_theme: cotes2020/jekyll-theme-chirpy

plugins:
  - jekyll-remote-theme

future: true
